### ISSUE TITLE
Migrate the lib for .NET Core

### ISSUE THREAD

**Issue by xtrmstep** [asmak9/CSVLibraryAK#1]
Hi,

Can it be migrated to .NET Core? I'm pretty interested in this because of related work. This lib is the best option among others as far as I see. Would be nice to have it migrated to support the latest version of .NET.

Thanks.

**Comment by asmak9** [comment]
Thank you for your interest and support. I will shortly migrate this library to .NET Core as well then let you know.

**Comment by asmak9** [comment]
.Net core version for this library is available now. You can download via Nuget i.e. https://www.nuget.org/packages/CSVLibraryAK.Core

**Comment by xtrmstep** [comment]
Thank you!
